=== Sydney-Informatics-Hub/Microscopy-Segmentation/tools/json_schema_anylabeling.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "flags": {
      "type": "object"
    },
    "shapes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string"
          },
          "text": {
            "type": "string"
          },
          "points": {
            "type": "array",
            "items": {
              "type": "array",
              "items": {
                "type": "number"
              }
            }
          },
          "group_id": {
            "type": ["object", "string", "null"],
            "description": "This can be any type"
          },
          "shape_type": {
            "type": "string"
          },
          "flags": {
            "type": "object"
          }
        },
        "required": ["label", "points", "shape_type"]
      }
    },
    "imagePath": {
      "type": "string"
    },
    "imageData": {
      "type": ["object","null","string"]
    },
    "imageHeight": {
      "type": "number"
    },
    "imageWidth": {
      "type": "number"
    }
  },
  "required": ["version", "shapes", "imagePath", "imageHeight", "imageWidth"]
}

=== Sydney-Informatics-Hub/Microscopy-Segmentation/testdata/sample_anylabeling/HM25_003.json
{
  "version": "0.3.3",
  "flags": {},
  "shapes": [
    {
      "label": "type1",
      "text": "",
      "points": [
        [
          928.0,
          789.0
        ],
        [
          910.0,
          789.0
        ],
        [
          896.0,
          793.0
        ],
        [
          852.0,
          812.0
        ],
        [
          832.0,
          829.0
        ],
        [
          777.0,
          862.0
        ],
        [
          750.0,
          890.0
        ],
        [
          723.0,
          930.0
        ],
        [
          716.0,
          953.0
        ],
        [
          714.0,
          983.0
        ],
        [
          699.0,
          1025.0
        ],
        [
          699.0,
          1086.0
        ],
        [
          702.0,
          1113.0
        ],
        [
          707.0,
          1136.0
        ],
        [
          728.0,
          1184.0
        ],
        [
          757.0,
          1228.0
        ],
        [
          795.0,
          1269.0
        ],
        [
          814.0,
          1281.0
        ],
        [
          874.0,
          1297.0
        ],
        [
          914.0,
          1298.0
        ],
        [
          953.0,
          1286.0
        ],
        [
          1004.0,
          1257.0
        ],
        [
          1035.0,
          1230.0
        ],
        [
          1065.0,
          1195.0
        ],
        [
          1103.0,
          1131.0
        ],
        [
          1110.0,
          1116.0
        ],
        [
          1128.0,
          1057.0
        ],
        [
          1126.0,
          1036.0
        ],
        [
          1108.0,
          998.0
        ],
        [
          1109.0,
          968.0
        ],
        [
          1105.0,
          953.0
        ],
        [
          1086.0,
          913.0
        ],
        [
          1072.0,
          893.0
        ],
        [
          1033.0,
          848.0
        ],
        [
          1027.0,
          838.0
        ],
        [
          1004.0,
          817.0
        ],
        [
          981.0,
          804.0
        ]
      ],
      "group_id": null,
      "shape_type": "polygon",
      "flags": {}
    },
    {
      "label": "type1",
      "text": "",
      "points": [
        [
          1713.0,
          850.0
        ],
        [
          1709.0,
          850.0
        ],
        [
          1708.0,
          849.0
        ],
        [
          1700.0,
          849.0
        ],
        [
          1699.0,
          848.0
        ],
        [
          1678.0,
          848.0
        ],
        [
          1677.0,
          849.0
        ],
        [
          1672.0,
          849.0
        ],
        [
          1671.0,
          850.0
        ],
        [
          1662.0,
          851.0
        ],
        [
          1648.0,
          857.0
        ],
        [
          1645.0,
          860.0
        ],
        [
          1637.0,
          864.0
        ],
        [
          1628.0,
          871.0
        ],
        [
          1624.0,
          873.0
        ],
        [
          1613.0,
          884.0
        ],
        [
          1603.0,
          899.0
        ],
        [
          1598.0,
          910.0
        ],
        [
          1596.0,
          920.0
        ],
        [
          1595.0,
          921.0
        ],
        [
          1595.0,
          924.0
        ],
        [
          1594.0,
          925.0
        ],
        [
          1593.0,
          937.0
        ],
        [
          1592.0,
          938.0
        ],
        [
          1593.0,
          954.0
        ],
        [
          1594.0,
          955.0
        ],
        [
          1594.0,
          959.0
        ],
        [
          1597.0,
          966.0
        ],
        [
          1597.0,
          969.0
        ],
        [
          1602.0,
          978.0
        ],
        [
          1620.0,
          998.0
        ],
        [
          1621.0,
          998.0
        ],
        [
          1632.0,
          1007.0
        ],
        [
          1640.0,
          1011.0
        ],
        [
          1642.0,
          1011.0
        ],
        [
          1649.0,
          1015.0
        ],
        [
          1651.0,
          1015.0
        ],
        [
          1664.0,
          1020.0
        ],
        [
          1685.0,
          1020.0
        ],
        [
          1686.0,
          1019.0
        ],
        [
          1692.0,
          1019.0
        ],
        [
          1693.0,
          1018.0
        ],
        [
          1700.0,
          1017.0
        ],
        [
          1701.0,
          1016.0
        ],
        [
          1724.0,
          1009.0
        ],
        [
          1739.0,
          1001.0
        ],
        [
          1748.0,
          993.0
        ],
        [
          1749.0,
          993.0
        ],
        [
          1759.0,
          983.0
        ],
        [
          1766.0,
          970.0
        ],
        [
          1768.0,
          960.0
        ],
        [
          1769.0,
          959.0
        ],
        [
          1769.0,
          956.0
        ],
        [
          1772.0,
          950.0
        ],
        [
          1772.0,
          947.0
        ],
        [
          1774.0,
          943.0
        ],
        [
          1775.0,
          935.0
        ],
        [
          1776.0,
          934.0
        ],
        [
          1776.0,
          929.0
        ],
        [
          1777.0,
          928.0
        ],
        [
          1776.0,
          926.0
        ],
        [
          1775.0,
          913.0
        ],
        [
          1774.0,
          912.0
        ],
        [
          1774.0,
          909.0
        ],
        [
          1773.0,
          908.0
        ],
        [
          1771.0,
          900.0
        ],
        [
          1763.0,
          886.0
        ],
        [
          1750.0,
          870.0
        ],
        [
          1744.0,
          867.0
        ],
        [
          1734.0,
          860.0
        ],
        [
          1725.0,
          856.0
        ],
        [
          1723.0,
          854.0
        ]
      ],
      "group_id": null,
      "shape_type": "polygon",
      "flags": {}
    },
    {
      "label": "type2",
      "text": "",
      "points": [
        [
          756.0,
          766.0
        ],
        [
          738.0,
          757.0
        ],
        [
          733.0,
          753.0
        ],
        [
          718.0,
          747.0
        ],
        [
          698.0,
          746.0
        ],
        [
          697.0,
          747.0
        ],
        [
          682.0,
          749.0
        ],
        [
          645.0,
          760.0
        ],
        [
          630.0,
          767.0
        ],
        [
          621.0,
          774.0
        ],
        [
          615.0,
          777.0
        ],
        [
          603.0,
          790.0
        ],
        [
          594.0,
          796.0
        ],
        [
          582.0,
          808.0
        ],
        [
          576.0,
          816.0
        ],
        [
          571.0,
          828.0
        ],
        [
          568.0,
          843.0
        ],
        [
          563.0,
          856.0
        ],
        [
          563.0,
          865.0
        ],
        [
          564.0,
          866.0
        ],
        [
          564.0,
          872.0
        ],
        [
          566.0,
          878.0
        ],
        [
          571.0,
          888.0
        ],
        [
          574.0,
          906.0
        ],
        [
          576.0,
          912.0
        ],
        [
          592.0,
          946.0
        ],
        [
          597.0,
          952.0
        ],
        [
          611.0,
          962.0
        ],
        [
          626.0,
          968.0
        ],
        [
          640.0,
          971.0
        ],
        [
          644.0,
          973.0
        ],
        [
          663.0,
          973.0
        ],
        [
          674.0,
          969.0
        ],
        [
          682.0,
          962.0
        ],
        [
          695.0,
          955.0
        ],
        [
          710.0,
          944.0
        ],
        [
          716.0,
          932.0
        ],
        [
          716.0,
          930.0
        ],
        [
          725.0,
          914.0
        ],
        [
          743.0,
          894.0
        ],
        [
          749.0,
          885.0
        ],
        [
          753.0,
          881.0
        ],
        [
          758.0,
          872.0
        ],
        [
          766.0,
          864.0
        ],
        [
          771.0,
          856.0
        ],
        [
          778.0,
          848.0
        ],
        [
          781.0,
          842.0
        ],
        [
          782.0,
          832.0
        ],
        [
          783.0,
          831.0
        ],
        [
          781.0,
          814.0
        ],
        [
          772.0,
          799.0
        ],
        [
          766.0,
          779.0
        ],
        [
          763.0,
          773.0
        ]
      ],
      "group_id": null,
      "shape_type": "polygon",
      "flags": {}
    },
    {
      "label": "type2",
      "text": "",
      "points": [
        [
          1647.0,
          616.0
        ],
        [
          1637.0,
          622.0
        ],
        [
          1619.0,
          637.0
        ],
        [
          1611.0,
          646.0
        ],
        [
          1603.0,
          651.0
        ],
        [
          1596.0,
          658.0
        ],
        [
          1585.0,
          674.0
        ],
        [
          1579.0,
          687.0
        ],
        [
          1571.0,
          718.0
        ],
        [
          1571.0,
          730.0
        ],
